name: resume-parser
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pytest
      - pytest-cov
      - mammoth
      - python-docx
      - pandas
      - numpy
      - regex
      - pyyaml
      - requests
      - tqdm
      - rich
