name: resume-parser
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rich
  - pyfiglet
  - pytest
  - python-docx
  - pdfplumber
  - spacy
  - pandas
  - tabulate
  - nltk
  - scikit-learn
  - openpyxl
  - pip
