name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup init micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=3.9
          init-shell: bash

      - name: Install package (editable) and dev tools
        shell: bash -l {0}
        run: |
          pip install -e .
          pip install -U pytest pytest-cov

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v --cov=resume_parser --cov-report=term-missing
EOF
