name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up micromamba (stable)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
          init-shell: bash
          create-args: python=3.10

      - name: Verify environment
        shell: "bash -l {0}"
        run: |
          micromamba info
          micromamba list

      - name: Run tests with coverage
        shell: "bash -l {0}"
        working-directory: .
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v --cov=resume_parser --cov-report=term-missing
